from yacs.config import CfgNode as CN

_C = CN()

# Drug feature extractor
_C.DRUG = CN()
_C.DRUG.NODE_IN_FEATS = 75

_C.DRUG.PADDING = True

_C.DRUG.HIDDEN_LAYERS = [128, 128,128]
_C.DRUG.NODE_IN_EMBEDDING = 128
_C.DRUG.MAX_NODES = 300

# Pre-extracted features settings
_C.PRETRAINED = CN()
_C.PRETRAINED.USE_ESM2 = False  
_C.PRETRAINED.USE_CHEMBERT = False  
_C.PRETRAINED.ESM2_DIM = 1280 
_C.PRETRAINED.CHEMBERT_DIM = 384  
_C.PRETRAINED.FEATURE_DIR = "../datasets/pre_data/Drugbank" 

# Protein feature extractor
_C.PROTEIN = CN()
_C.PROTEIN.NUM_FILTERS = [128]
_C.PROTEIN.EMBEDDING_DIM = 128
_C.PROTEIN.NUM_HEAD = 4
_C.PROTEIN.PADDING = True

# CrossIntention feature fusion
# CrossIntention feature fusion
_C.AGICA_CROSS_ATTENTION = CN()
_C.AGICA_CROSS_ATTENTION.NUM_HEAD = 4
_C.AGICA_CROSS_ATTENTION.EMBEDDING_DIM = 128
_C.AGICA_CROSS_ATTENTION.AGICA_DROPOUT_RATE = 0.1

# MLP decoder
_C.DECODER = CN()
_C.DECODER.NAME = "MPRC"
_C.DECODER.IN_DIM = 384
_C.DECODER.HIDDEN_DIM = 768
_C.DECODER.OUT_DIM = 384
_C.DECODER.BINARY = 1
_C.DECODER.DROPOUT_RATE = 0.02
# SOLVER
_C.SOLVER = CN()
_C.SOLVER.MAX_EPOCH = 100
_C.SOLVER.BATCH_SIZE = 64
_C.SOLVER.NUM_WORKERS = 8
_C.SOLVER.LR = 1e-4
_C.SOLVER.USE_LD = True
_C.SOLVER.LR_DECAY = 0.5
_C.SOLVER.DECAY_INTERVAL =25
_C.SOLVER.WEIGHT_DECAY = 1e-5
_C.SOLVER.SEED = 42

_C.SOLVER.PATIENCE = 15
_C.SOLVER.MIN_DELTA = 0.001 
_C.SOLVER.MONITOR = 'auroc'
_C.SOLVER.MODE = 'max' 
# RESULT
_C.RESULT = CN()
_C.RESULT.OUTPUT_DIR = r"../output/result/"
_C.RESULT.SAVE_MODEL = True

def get_cfg_defaults():
    return _C.clone()
